apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: devops-monitoring
  labels:
    app.kubernetes.io/name: influxdb
spec:
  ipFamilies:
  - IPv4
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: influxdb